### ISSUE TITLE
Didn't Clean Minicart Items

### ISSUE THREAD

**Issue by thien321091** [breadfinance/magento-v2-bread#130]
Hi Bread Team
I got a problem with bread after enabled Catalog Product View button, After redirect to checkout/success page but the mini cart didn't clean

![screenshot-2019 11 11-18_01_34](https://user-images.githubusercontent.com/3570575/68582714-00a73480-04ae-11ea-8719-825a2263a587.png)

Thanks
Hidro Le

**Comment by dfroneberger** [comment]
Hi, I believe this issue has been resolved as an issue originating from the merchant's site rather than the plugin, so closing this out
