### ISSUE TITLE
broken script if bread checkout is undefined

### ISSUE THREAD

**Issue by bartdominiak** [breadfinance/magento-v2-bread#59]
For some reason if bread object isn't created then our app will be broken and stop. So it's necessary to wrap `bread.checkout(breadConfig)` as a condition

```js
if (typeof bread !== 'undefined') { 
  bread.checkout(breadConfig);
}

**Comment by dfroneberger** [comment]
Thanks! We'll add that check in just to be safe in those cases in our next version of the plugin
