### ISSUE TITLE
getAllowCheckout() undefined

### ISSUE THREAD

**Issue by bartdominiak** [breadfinance/magento-v2-bread#75]
`allowCheckout: false` is hardcoded on product list grid view, it should be extended with getAllowCheckout() method like in product-view.

Admin Panel view
![test](https://user-images.githubusercontent.com/18058305/61716028-97fd4600-ad5e-11e9-81de-8db305dd0eb3.png)

**Comment by dfroneberger** [comment]
This is actually intended functionality to not allow checkout from the product list grid view, so that's why that value is hardcoded to false.
